---
- name: create systemd unit file
  template:
    src: embyserver.systemd.j2
    dest: "/etc/systemd/system/{{ embyserver_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify: Restart embyserver service

- name: create config volume directory
  file:
    path: "{{ embyserver_config_volume_directory }}"
    state: directory
    owner: "{{ embyserver_user_id | int }}"
    group: "{{ embyserver_group_id | int }}"
    mode: 0750

- name: create transcoding-temp volume directory
  file:
    path: "{{ embyserver_transcoding_temp_volume_directory }}"
    state: directory
    owner: "{{ embyserver_user_id | int }}"
    group: "{{ embyserver_group_id | int }}"
    mode: 0750
  when: embyserver_transcoding_temp_volume_directory is defined
    and embyserver_transcoding_temp_volume_directory | length > 0

- name: create log volume directory
  file:
    path: "{{ embyserver_log_volume_directory }}"
    state: directory
    owner: "{{ embyserver_user_id | int }}"
    group: "{{ embyserver_group_id | int }}"
    mode: 0750
  when: embyserver_log_volume_directory is defined
    and embyserver_log_volume_directory | length > 0

- name: Start systemd-managed docker containers
  meta: flush_handlers

- name: Enable/start systemd service (if not started)
  service:
    name: "{{ embyserver_service_name }}.service"
    enabled: true
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
