---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/shared/requirements.yml

lint: |
  set -e
  yamllint .
  ansible-lint

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: ansible-embyserver-focal
    box: generic/ubuntu2004

provisioner:
  name: ansible
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
